export const BIST30 = ['AKBNK','BEKO','ASELS','BIMAS','EKGYO','EREGL','FROTO','GARAN','GUBRF','HEKTS','KCHOL','PETKM','PGSUS','SAHOL','SISE','TAVHL','TCELL','THYAO','TOASO','TUPRS','VESTL','YKBNK'];

export const DEFAULT_SAMPLE = BIST30;
const BIST50_EXTRA = ['AEFES','AKSA','ALARK','AYGAZ','CCOLA','DOHOL','ENKAI','GESAN','HALKB','ISGYO','KONTR','LOGO','MPARK','NETAS','OTKAR','OYAKC','SARKY','SOKM','TTKOM','VAKBN'];
const BIST100_EXTRA = ['ADEL','AFYON','AGESA','AKCNS','AKENR','AKFGY','ALGYO','ALKIM','ANHYT','ANSGR','AYDEM','BASGZ','BIENY','BRISA','BRYAT','BUCIM','CANTE','CEMTS','CIMSA','DOAS','EGEEN','ENJSA','EUPWR','GENIL','GLYHO','GOZDE','GSDHO','INDES','ISMEN','KARSN','KLSER','KORDS','MAVI','OBAMS','SELEC','SKBNK','SNGYO','TATGD','TMSN','TRGYO','TSKB','TTRAK','TURSG','ULKER','ULUUN','VERUS','YATAS'];
const BISTALL_EXTRA = ['A1CAP','A1YEN','AAGYO','ACSEL','ADEL','ADESE','ADGYO','AEFES','AFYON','AGESA','AGHOL','AGROT','AGYO','AHGAZ','AHSGY','AKBNK','AKCNS','AKENR','AKFGY','AKFIS','AKFYE','AKGRT','AKHAN','AKMGY','AKSA','AKSEN','AKSGY','AKSUE','AKYHO','ALARK','ALBRK','ALCAR','ALCTL','ALFAS','ALGYO','ALKA','ALKIM','ALKLC','ALTNY','ALVES','ANELE','ANGEN','ANHYT','ANSGR','APBDL','APGLD','APLIB','APMDL','APX30','ARASE','BEKO','ARDYZ','ARENA','ARFYE','ARMGD','ARSAN','ARTMS','ARZUM','ASELS','ASGYO','ASTOR','ASUZU','ATAGY','ATAKP','ATATP','ATATR','ATEKS','ATLAS','ATSYH','AVGYO','AVHOL','AVOD','AVPGY','AVTUR','AYCES','AYDEM','AYEN','AYES','AYGAZ','AZTEK','BAGFS','BAHKM','BAKAB','BALAT','BALSU','BANVT','BARMA','BASCM','BASGZ','BAYRK','BEGYO','BERA','BESLR','BESTE','BEYAZ','BFREN','BIENY','BIGCH','BIGEN','BIGTK','BIMAS','BINBN','BINHO','BIOEN','BIZIM','BJKAS','BLCYT','BLUME','BMSCH','BMSTL','BNTAS','BOBET','BORLS','BORSK','BOSSA','BRISA','BRKO','BRKSN','BRKVY','BRLSM','BRMEN','BRSAN','BRYAT','BSOKE','BTCIM','BUCIM','BULGS','BURCE','BURVA','BVSAN','BYDNR','CANTE','CATES','CCOLA','CELHA','CEMAS','CEMTS','CEMZY','CEOEM','CGCAM','CIMSA','CLEBI','CMBTN','CMENT','CONSE','COSMO','CRDFA','CRFSA','CUSAN','CVKMD','CWENE','DAGI','DAPGM','DARDL','DCTTR','DENGE','DERHL','DERIM','DESA','DESPC','DEVA','DGATE','DGGYO','DGNMO','DIRIT','DITAS','DMRGD','DMSAS','DNISI','DOAS','DOCO','DOFER','DOFRB','DOGUB','DOHOL','DOKTA','DSTKF','DUNYH','DURDO','DURKN','DYOBY','DZGYO','EBEBK','ECILC','ECOGR','ECZYT','EDATA','EDIP','EFOR','EGEEN','EGEGY','EGEPO','EGGUB','EGPRO','EGSER','EKGYO','EKIZ','EKOS','EKSUN','ELITE','EMKEL','EMNIS','EMPAE','ENDAE','ENERY','ENJSA','ENKAI','ENPRA','ENRYA','ENSRI','ENTRA','EPLAS','ERBOS','ERCB','EREGL','ERSU','ESCAR','ESCOM','ESEN','ETILR','ETYAT','EUHOL','EUKYO','EUPWR','EUREN','EUYO','EYGYO','FADE','FENER','FLAP','FMIZP','FONET','FORMT','FORTE','FRIGO','FRMPL','FROTO','FZLGY','GARAN','GARFA','GATEG','GEDIK','GEDZA','GENIL','GENKM','GENTS','GEREL','GESAN','GIPTA','GLBMD','GLCVY','GLDTR','GLRMK','GLRYH','GLYHO','GMSTR','GMSTRF','GMTAS','GOKNR','GOLTS','GOODY','GOZDE','GRNYO','GRSEL','GRTHO','GSDDE','GSDHO','GSRAY','GUBRF','GUNDG','GWIND','GZNMI','HALKB','HATEK','HATSN','HDFGS','HEDEF','HEKTS','HKTM','HLGYO','HOROZ','HRKET','HTTBT','HUBVC','HUNER','HURGZ','ICBCT','ICUGS','IDGYO','IEYHO','IHAAS','IHEVA','IHGZT','IHLAS','IHLGM','IHYAY','IMASM','INDES','INFO','INGRM','INTEK','INTEM','INVEO','INVES','ISATR','ISBIR','ISBTR','ISCTR','ISDMR','ISFIN','ISGLK','ISGSY','ISGYO','ISKPL','ISKUR','ISMEN','ISSEN','ISYAT','IZENR','IZFAS','IZINV','IZMDC','JANTS','KAPLM','KAREL','KARSN','KARTN','KATMR','KAYSE','KBORU','KCAER','KCHOL','KENT','KERVN','KFEIN','KGYO','KIMMR','KLGYO','KLKIM','KLMSN','KLNMA','KLRHO','KLSER','KLSYN','KLYPV','KMPUR','KNFRT','KOCMT','KONKA','KONTR','KONYA','KOPOL','KORDS','KOTON','KRDMA','KRDMB','KRDMD','KRGYO','KRONT','KRPLS','KRSTL','KRTEK','KRVGD','KSTUR','KTLEV','KTSKR','KUTPO','KUVVA','KUYAS','KZBGY','KZGYO','LIDER','LIDFA','LILAK','LINK','LKMNH','LMKDC','LOGO','LRSHO','LUKSK','LXGYO','LYDHO','LYDIA','LYDYE','MAALT','MACKO','MAGEN','MAKIM','MAKTK','MANAS','MARBL','MARKA','MARMR','MARTI','MAVI','MCARD','MEDTR','MEGAP','MEGMT','MEKAG','MEPET','MERCN','MERIT','MERKO','METRO','MEYSU','MGROS','MHRGY','MIATK','MMCAS','MNDRS','MNDTR','MOBTL','MOGAN','MOPAS','MPARK','MRGYO','MRSHL','MSGYO','MTRKS','MTRYO','MZHLD','NATEN','NETAS','NETCD','NIBAS','NPTLR','NTGAZ','NTHOL','NUGYO','NUHCM','OBAMS','OBASE','ODAS','ODINE','OFSYM','ONCSM','ONRYT','OPK30','OPT25','OPTGY','OPTLR','OPX30','ORCAY','ORGE','ORMA','OSMEN','OSTIM','OTKAR','OTTO','OYAKC','OYAYO','OYLUM','OYYAT','OZATD','OZGYO','OZKGY','OZRDN','OZSUB','OZYSR','PAGYO','PAHOL','PAMEL','PAPIL','PARSN','PASEU','PATEK','PCILT','PEKGY','PENGD','PENTA','PETKM','PETUN','PGSUS','PINSU','PKART','PKENT','PLTUR','PNLSN','PNSUT','POLHO','POLTK','PRDGS','PRKAB','PRKME','PRZMA','PSDTC','PSGYO','QNBFK','QNBTR','QTEMZ','QUAGR','RALYH','RAYSG','REEDR','RGYAS','RNPOL','RODRG','ROYAL','RTALB','RUBNS','RUZYE','RYGYO','RYSAS','SAFKR','SAHOL','SAMAT','SANEL','SANFM','SANKO','SARKY','SASA','SAYAS','SDTTR','SEGMN','SEGYO','SEKFK','SEKUR','SELEC','SELVA','SERNT','SEYKM','SILVR','SISE','SKBNK','SKTAS','SKYLP','SKYMD','SMART','SMRTG','SMRVA','SNGYO','SNICA','SNPAM','SODSN','SOKE','SOKM','SONME','SRVGY','SUMAS','SUNTK','SURGY','SUWEN','SVGYO','TABGD','TARKM','TATEN','TATGD','TAVHL','TBORG','TCELL','TCKRC','TDGYO','TEHOL','TEKTU','TERA','TEZOL','TGSAS','THYAO','TKFEN','TKNSA','TLMAN','TMPOL','TMSN','TNZTP','TOASO','TRALT','TRCAS','TRENJ','TRGYO','TRHOL','TRILC','TRMET','TSGYO','TSKB','TSPOR','TTKOM','TTRAK','TUCLK','TUKAS','TUPRS','TUREX','TURGG','TURSG','UCAYM','UFUK','ULAS','ULKER','ULUFA','ULUSE','ULUUN','UMPAS','UNLU','USAK','USDTR','USDTRF','VAKBN','VAKFA','VAKFN','VAKKO','VANGD','VBTYZ','VERTU','VERUS','VESBE','VESTL','VKFYO','VKGYO','VKING','VRGYO','VSNMD','YAPRK','YATAS','YAYLA','YBTAS','YEOTK','YESIL','YGGYO','YIGIT','YKBNK','YKSLN','YONGA','YUNSA','YYAPI','YYLGD','Z30EA','Z30KE','Z30KP','ZEDUR','ZELOT','ZERGY','ZGOLD','ZGOLDF','ZGYO','ZOREN','ZPBDL','ZPLIB','ZPT10','ZPX30','ZRE20','ZRGYO','ZSR25','ZTLRF','ZTLRK','ZTM25'];

export function getStockList(listType) {
  const clean = arr => [...new Set(arr.map(s => s.trim()).filter(Boolean))];
  const bist50 = clean([...BIST30, ...BIST50_EXTRA]);
  const bist100 = clean([...bist50, ...BIST100_EXTRA]);
  const bistAll = clean([...bist100, ...BISTALL_EXTRA]);
  switch (listType) {
    case 'bist30': return clean([...BIST30]);
    case 'bist50': return bist50;
    case 'bist100': return bist100;
    case 'bistall': return bistAll;
    default: return bist100;
  }
}

export const QUICK_STOCKS = ['THYAO','ASELS','PETKM','AKBNK','EREGL','TOASO','SISE','GARAN','TUPRS','KCHOL','SAHOL','BIMAS'];

export const SECTORS = {
  THYAO:'Havayolu',PGSUS:'Havayolu',TAVHL:'Havayolu',ASELS:'Savunma',
  KCHOL:'Holding',SAHOL:'Holding',DOHOL:'Holding',GLYHO:'Holding',GOZDE:'Holding',GSDHO:'Holding',
  AKBNK:'Banka',GARAN:'Banka',ISCTR:'Banka',YKBNK:'Banka',HALKB:'Banka',VAKBN:'Banka',SKBNK:'Banka',TSKB:'Banka',ALBRK:'Banka',
  PETKM:'Petrokimya',TUPRS:'Petrokimya',SASA:'Petrokimya',
  TOASO:'Otomotiv',FROTO:'Otomotiv',DOAS:'Otomotiv',OTKAR:'Otomotiv',
  EREGL:'Metal',KRDMD:'Metal',CEMTS:'Metal',SISE:'Cam/Sanayi',
  ARCLK:'Beyaz Esya',BEKO:'Beyaz Esya',VESTL:'Beyaz Esya',
  BIMAS:'Perakende',MGROS:'Perakende',SOKM:'Perakende',
  TCELL:'Telekom',TTKOM:'Telekom',
  EKGYO:'GYO',ISGYO:'GYO',TRGYO:'GYO',SNGYO:'GYO',
  GUBRF:'Gubre/Kimya',HEKTS:'Gubre/Kimya',KOZAA:'Madencilik',KOZAL:'Madencilik',
  ENKAI:'Insaat',TKFEN:'Insaat',GESAN:'Insaat',
  CCOLA:'Gida',ULKER:'Gida',TATGD:'Gida',AEFES:'Gida',
  LOGO:'Teknoloji',NETAS:'Teknoloji',INDES:'Teknoloji',
  MAVI:'Tekstil',BRISA:'Lastik',KORDS:'Lastik',AKSA:'Kimya',ALKIM:'Kimya',
  ODAS:'Enerji',AKENR:'Enerji',ENJSA:'Enerji',AYDEM:'Enerji',EUPWR:'Enerji',
  AGESA:'Sigorta',ANHYT:'Sigorta',ANSGR:'Sigorta',TURSG:'Sigorta'
};
