// ════════════════════════════════════════════════════════════════════
// DatabaseManager.js — Persistent SQLite Layer for Self-Learning Engine
// ════════════════════════════════════════════════════════════════════
//
// Architecture:
//   Electron main process → better-sqlite3 (synchronous, ~50x faster than sql.js)
//   Renderer process     → IPC bridge via window.electronAPI.mlDb.*
//   Fallback (web/dev)   → sql.js with localStorage (existing database.js)
//
// Tables:
//   trade_signals       — every signal generated by genSignal, with technical snapshot
//   signal_outcomes     — T+1 / T+3 / T+5 actual ROI filled by backtest engine
//   discovered_rules    — autonomous combinatorial rule results
//   feature_importance  — per-feature predictive power (information gain)
//
// All writes use WAL mode + transactions for max throughput.
// ════════════════════════════════════════════════════════════════════

const DB_VERSION = 4;
const DB_FILENAME = 'bist_ml_engine.db';

// ── SCHEMA ─────────────────────────────────────────────────────────

const SCHEMA_SQL = `
  -- Core signal log: every buy/sell/hold signal ever generated
  CREATE TABLE IF NOT EXISTS trade_signals (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol          TEXT    NOT NULL,
    ts              INTEGER NOT NULL,          -- Unix ms timestamp
    direction       TEXT    NOT NULL,          -- BUY / SELL / HOLD
    score100        REAL,                      -- genSignal normalized 0-100
    raw_score       REAL,                      -- raw accumulator (-35..+35)
    entry_price     REAL    NOT NULL,
    stop_price      REAL,
    target_price    REAL,
    rr              REAL,                      -- reward/risk ratio
    atr             REAL,
    atr_pct         REAL,
    -- Technical state snapshot (dense numeric columns for fast SQL aggregation)
    rsi             REAL,
    mfi             REAL,
    adx             REAL,
    cmf             REAL,
    vol_ratio       REAL,
    boll_pct        REAL,                      -- price position within Bollinger bands (0-100)
    dist_ma20_pct   REAL,                      -- distance from MA20 in %
    dist_ma50_pct   REAL,
    dist_ma200_pct  REAL,
    obv_trend       TEXT,                      -- accumulation / distribution / neutral
    wyckoff_phase   TEXT,
    supertrend_dir  TEXT,                      -- UP / DOWN
    ichimoku_pos    TEXT,                      -- above / below / inside
    ttm_squeeze     INTEGER DEFAULT 0,         -- 1 if squeezeOn
    ttm_fire        INTEGER DEFAULT 0,         -- 1 if squeeze just fired
    -- Fired signals bitmap (JSON array of signal type strings)
    fired_signals   TEXT,                      -- '["RSI_OVERSOLD","MACD_BULL_CROSS",...]'
    -- Regime & meta
    regime          TEXT,                      -- TREND / VOLATILE / CHOPPY / QUIET
    setup_grade     TEXT,                      -- A / B / C / D
    sector          TEXT,
    -- Outcome columns (filled async by backtest engine)
    actual_t1_roi   REAL,                      -- T+1 day ROI %
    actual_t3_roi   REAL,                      -- T+3 day ROI %
    actual_t5_roi   REAL,                      -- T+5 day ROI %
    outcome         TEXT,                      -- WIN / LOSS / OPEN / EXPIRED
    outcome_ts      INTEGER,                   -- when outcome was determined
    -- Technical state as full JSON (for complex queries / future features)
    technical_state TEXT                        -- full ind snapshot JSON
  );

  -- Combinatorial rule discovery results
  CREATE TABLE IF NOT EXISTS discovered_rules (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    rule_hash       TEXT    UNIQUE NOT NULL,    -- deterministic hash of the combo
    setup_name      TEXT    NOT NULL,           -- human-readable: "RSI_OVERSOLD + OBV_ACC + BB_SQUEEZE"
    conditions      TEXT    NOT NULL,           -- JSON array of {feature, op, value}
    direction       TEXT    DEFAULT 'BUY',      -- which direction this rule fires for
    total_count     INTEGER DEFAULT 0,
    win_count       INTEGER DEFAULT 0,
    loss_count      INTEGER DEFAULT 0,
    win_rate_pct    REAL    DEFAULT 0,
    avg_roi_pct     REAL    DEFAULT 0,
    avg_win_roi     REAL    DEFAULT 0,
    avg_loss_roi    REAL    DEFAULT 0,
    expectancy      REAL    DEFAULT 0,          -- avg_win * winRate + avg_loss * lossRate
    sharpe          REAL    DEFAULT 0,          -- risk-adjusted return
    max_drawdown    REAL    DEFAULT 0,
    profit_factor   REAL    DEFAULT 0,          -- gross_wins / gross_losses
    last_updated    INTEGER,
    created_at      INTEGER,                    -- first discovery timestamp
    last_seen_date  INTEGER,                    -- last training run where this rule fired
    regime_tags     TEXT,                        -- JSON array of market regimes where rule works
    is_active       INTEGER DEFAULT 1           -- 0 = archived
  );

  -- Per-feature predictive power tracking
  CREATE TABLE IF NOT EXISTS feature_importance (
    feature_name    TEXT    PRIMARY KEY,
    direction       TEXT    DEFAULT 'BUY',
    info_gain       REAL    DEFAULT 0,          -- information gain vs random
    correlation     REAL    DEFAULT 0,          -- Pearson corr with next-day ROI
    sample_count    INTEGER DEFAULT 0,
    last_updated    INTEGER
  );

  -- Paper trading portfolio state
  CREATE TABLE IF NOT EXISTS paper_portfolio (
    id              INTEGER PRIMARY KEY CHECK (id = 1),  -- singleton row
    cash            REAL    NOT NULL DEFAULT 100000,
    start_capital   REAL    NOT NULL DEFAULT 100000,
    start_date      INTEGER NOT NULL,
    total_trades    INTEGER DEFAULT 0,
    wins            INTEGER DEFAULT 0,
    losses          INTEGER DEFAULT 0,
    total_pnl       REAL    DEFAULT 0,
    max_drawdown    REAL    DEFAULT 0,
    peak_equity     REAL    DEFAULT 100000,
    last_updated    INTEGER
  );

  -- Paper trading individual trades
  CREATE TABLE IF NOT EXISTS paper_trades (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol          TEXT    NOT NULL,
    direction       TEXT    NOT NULL DEFAULT 'BUY',
    status          TEXT    NOT NULL DEFAULT 'OPEN',  -- OPEN / CLOSED
    entry_price     REAL    NOT NULL,
    exit_price      REAL,
    stop_price      REAL    NOT NULL,
    target_price    REAL,
    size_tl         REAL    NOT NULL,                 -- position size in TL
    lots            INTEGER DEFAULT 0,
    pnl_tl          REAL,
    pnl_pct         REAL,
    exit_reason     TEXT,                              -- STOP / TARGET / MANUAL / EOD / TRAILING
    -- ML context at entry
    ml_confidence   REAL,                              -- mlConfidenceBoost at entry
    ml_best_rule    TEXT,                              -- best matching ML rule name
    ml_matched      INTEGER DEFAULT 0,                 -- mlMatchedCount
    confidence      REAL,                              -- composite confidence score
    grade           TEXT,                              -- A/B/C/D
    tier            TEXT,                              -- STRONG/GOOD/FAIR/WEAK
    score100        REAL,
    rr              REAL,
    sector          TEXT,
    fired_signals   TEXT,                              -- JSON array
    -- Timestamps
    opened_at       INTEGER NOT NULL,
    closed_at       INTEGER,
    held_ms         INTEGER,
    -- Extra context
    entry_atr_pct   REAL,
    entry_rsi       REAL,
    entry_regime    TEXT,
    notes           TEXT
  );

  -- Schema version tracker
  CREATE TABLE IF NOT EXISTS db_meta (
    key   TEXT PRIMARY KEY,
    value TEXT
  );

  -- Performance indices
  CREATE INDEX IF NOT EXISTS idx_ts_symbol      ON trade_signals(symbol, ts);
  CREATE INDEX IF NOT EXISTS idx_ts_direction   ON trade_signals(direction, ts);
  CREATE INDEX IF NOT EXISTS idx_ts_outcome     ON trade_signals(outcome);
  CREATE INDEX IF NOT EXISTS idx_ts_score       ON trade_signals(score100);
  CREATE INDEX IF NOT EXISTS idx_ts_regime      ON trade_signals(regime);
  CREATE INDEX IF NOT EXISTS idx_ts_sector      ON trade_signals(sector);
  CREATE INDEX IF NOT EXISTS idx_rules_winrate  ON discovered_rules(win_rate_pct DESC);
  CREATE INDEX IF NOT EXISTS idx_rules_active   ON discovered_rules(is_active, win_rate_pct DESC);
  CREATE INDEX IF NOT EXISTS idx_pt_status      ON paper_trades(status);
  CREATE INDEX IF NOT EXISTS idx_pt_symbol      ON paper_trades(symbol, status);
  CREATE INDEX IF NOT EXISTS idx_pt_opened      ON paper_trades(opened_at DESC);
`;

// ════════════════════════════════════════════════════════════════════
// NODE.JS (Electron Main Process) Implementation
// ════════════════════════════════════════════════════════════════════

let _db = null;
let _isNode = false;

// Detect environment
try {
  _isNode = typeof process !== 'undefined' && process.versions?.node;
} catch { _isNode = false; }

// Build a require() function that works in both CJS and ESM contexts.
// In CJS (Electron main.cjs via dynamic import): global require may exist.
// In ESM (scripts, Vite): use createRequire(import.meta.url).
// NOTE: No top-level await — Vite browser build cannot handle TLA with es2020 target.
// Instead, _ensureNodeRequire() is called lazily from initMLDatabase().
let _nodeRequire = null;
try {
  if (typeof require === 'function') {
    _nodeRequire = require;
  }
} catch {}

async function _ensureNodeRequire() {
  if (_nodeRequire) return;
  if (!_isNode) return;
  try {
    // import.meta.url is available at parse time in ESM modules.
    // module.createRequire is synchronous.
    const { createRequire } = await import(/* @vite-ignore */ 'node:module');
    _nodeRequire = createRequire(import.meta.url);
  } catch {}
}

/**
 * Initialize the database. In Electron main: better-sqlite3 on disk.
 * In browser: falls back to sql.js + localStorage via existing database.js.
 * @param {string} [dbPath] - override DB file path (for testing)
 * @returns {object} db instance
 */
export async function initMLDatabase(dbPath) {
  if (_db) return _db;

  // Lazy require resolution — avoids TLA which breaks Vite browser build
  await _ensureNodeRequire();

  if (_isNode) {
    return _initBetterSqlite(dbPath);
  }
  // Browser fallback: use in-memory wrapper that matches the same API
  return _initBrowserFallback();
}

function _initBetterSqlite(dbPath) {
  if (!_nodeRequire) throw new Error('Cannot load better-sqlite3: no require() available. Run: npm install better-sqlite3');

  const Database = _nodeRequire('better-sqlite3');
  const path = _nodeRequire('path');
  const fs = _nodeRequire('fs');

  let dir = dbPath;
  if (!dir) {
    try {
      const { app } = _nodeRequire('electron');
      dir = path.join(app.getPath('userData'), DB_FILENAME);
    } catch {
      // Not in Electron (standalone script) — use cwd/data/
      dir = path.join(process.cwd(), 'data', DB_FILENAME);
    }
  }
  _db = new Database(dir);

  // Performance pragmas
  _db.pragma('journal_mode = WAL');      // Write-Ahead Logging
  _db.pragma('synchronous = NORMAL');    // Safe enough with WAL
  _db.pragma('cache_size = -64000');     // 64MB page cache
  _db.pragma('temp_store = MEMORY');     // temp tables in RAM
  _db.pragma('mmap_size = 268435456');   // 256MB memory-mapped I/O

  // Run schema
  _db.exec(SCHEMA_SQL);

  // Version migration
  const verRow = _db.prepare("SELECT value FROM db_meta WHERE key = 'schema_version'").get();
  const currentVer = verRow ? parseInt(verRow.value, 10) : 0;
  if (currentVer < DB_VERSION) {
    _runMigrations(_db, currentVer, DB_VERSION);
    _db.prepare("INSERT OR REPLACE INTO db_meta (key, value) VALUES ('schema_version', ?)")
      .run(String(DB_VERSION));
  }

  // ── AUTO-IMPORT: If our DB has no rules, try importing from training DB ──
  // Training scripts write to data/bist_ml_training.db (project root).
  // Electron runtime uses app.getPath('userData')/bist_ml_engine.db.
  // Bridge the gap: copy discovered_rules + feature_importance if they exist.
  try {
    const ruleCount = _db.prepare('SELECT COUNT(*) as cnt FROM discovered_rules').get()?.cnt || 0;
    if (ruleCount === 0) {
      // Search for training DB in common locations
      // Training scripts may use different DB names — check all variants
      const TRAINING_DB_NAMES = ['bist_ml_training.db', 'bist_ml_training_3yr.db'];
      const candidates = [];
      for (const name of TRAINING_DB_NAMES) {
        candidates.push(path.join(process.cwd(), 'data', name));
        candidates.push(path.join(path.dirname(dir), name));
      }
      // When running as packaged Electron app, check resources + app.asar paths
      try {
        const { app } = _nodeRequire('electron');
        for (const name of TRAINING_DB_NAMES) {
          candidates.push(path.join(app.getAppPath(), 'data', name));
          candidates.push(path.join(path.dirname(app.getPath('exe')), 'data', name));
        }
      } catch {}

      let _importedRules = 0;
      for (const trainDbPath of candidates) {
        if (fs.existsSync(trainDbPath)) {
          console.log(`[MLDb] Found training DB at ${trainDbPath} — importing rules...`);
          try {
            const trainDb = new Database(trainDbPath, { readonly: true });
            const rules = trainDb.prepare('SELECT * FROM discovered_rules WHERE is_active = 1').all();
            if (rules.length > 0) {
              const insert = _db.prepare(`
                INSERT OR IGNORE INTO discovered_rules
                  (rule_hash, setup_name, conditions, direction,
                   total_count, win_count, loss_count, win_rate_pct,
                   avg_roi_pct, avg_win_roi, avg_loss_roi,
                   expectancy, sharpe, max_drawdown, profit_factor,
                   last_updated, created_at, last_seen_date, is_active)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
              `);
              const tx = _db.transaction(() => {
                for (const r of rules) {
                  insert.run(
                    r.rule_hash, r.setup_name, r.conditions, r.direction || 'BUY',
                    r.total_count || 0, r.win_count || 0, r.loss_count || 0,
                    r.win_rate_pct || 0, r.avg_roi_pct || 0,
                    r.avg_win_roi || 0, r.avg_loss_roi || 0,
                    r.expectancy || 0, r.sharpe || 0,
                    r.max_drawdown || 0, r.profit_factor || 0,
                    r.last_updated || Date.now(),
                    r.created_at || Date.now(),
                    r.last_seen_date || Date.now()
                  );
                }
              });
              tx();
              _importedRules = rules.length;
              console.log(`[MLDb] Imported ${rules.length} rules from training DB`);
            } else {
              console.log(`[MLDb] Training DB at ${trainDbPath} has 0 active rules — trying next candidate`);
            }
            // Also import feature importance if available
            try {
              const feats = trainDb.prepare('SELECT * FROM feature_importance').all();
              if (feats.length > 0) {
                const fInsert = _db.prepare(`
                  INSERT OR REPLACE INTO feature_importance
                    (feature_name, info_gain, correlation, sample_count, last_updated)
                  VALUES (?, ?, ?, ?, ?)
                `);
                const ftx = _db.transaction(() => {
                  for (const f of feats) {
                    fInsert.run(f.feature_name, f.info_gain, f.correlation, f.sample_count, f.last_updated || Date.now());
                  }
                });
                ftx();
                console.log(`[MLDb] Imported ${feats.length} feature importance records`);
              }
            } catch {}
            trainDb.close();
          } catch (importErr) {
            console.warn(`[MLDb] Training DB import failed:`, importErr?.message);
          }
          // Only stop once we actually imported rules — an existing-but-empty
          // training DB (e.g. bist_ml_training.db with 0 rules) must NOT block
          // the next candidate (bist_ml_training_3yr.db with the real rules).
          if (_importedRules > 0) break;
        }
      }
    }
  } catch (autoImportErr) {
    console.warn('[MLDb] Auto-import check skipped:', autoImportErr?.message);
  }

  console.log(`[MLDb] better-sqlite3 initialized at ${dir} (v${DB_VERSION})`);
  return _wrapApi(_db);
}

function _runMigrations(db, from, to) {
  // Incremental ALTER TABLE migrations
  if (from < 2) {
    try { db.exec('ALTER TABLE trade_signals ADD COLUMN technical_state TEXT'); } catch {}
  }
  if (from < 3) {
    // v3: Rule memory columns — enable weighted merge for continuous learning
    try { db.exec('ALTER TABLE discovered_rules ADD COLUMN created_at INTEGER'); } catch {}
    try { db.exec('ALTER TABLE discovered_rules ADD COLUMN last_seen_date INTEGER'); } catch {}
    try { db.exec('ALTER TABLE discovered_rules ADD COLUMN regime_tags TEXT'); } catch {}
    // Backfill created_at from last_updated for existing rows
    try { db.exec('UPDATE discovered_rules SET created_at = last_updated WHERE created_at IS NULL'); } catch {}
    try { db.exec('UPDATE discovered_rules SET last_seen_date = last_updated WHERE last_seen_date IS NULL'); } catch {}
    // Index for decay queries (rules not seen in recent training runs)
    try { db.exec('CREATE INDEX IF NOT EXISTS idx_rules_last_seen ON discovered_rules(last_seen_date)'); } catch {}
    console.log('[MLDb] Migration v3: added rule memory columns (created_at, last_seen_date, regime_tags)');
  }
  if (from < 4) {
    // v4: Paper trading tables — schema already created above via CREATE TABLE IF NOT EXISTS
    // Initialize singleton portfolio row if missing
    try {
      const exists = db.prepare('SELECT id FROM paper_portfolio WHERE id = 1').get();
      if (!exists) {
        db.prepare(`INSERT INTO paper_portfolio (id, cash, start_capital, start_date, last_updated)
                     VALUES (1, 100000, 100000, ?, ?)`).run(Date.now(), Date.now());
      }
    } catch {}
    console.log('[MLDb] Migration v4: paper_portfolio + paper_trades tables');
  }
}

// ── Browser Fallback (sql.js localStorage) ─────────────────────────

function _initBrowserFallback() {
  const LS_KEY = 'bist_ml_signals_v2';
  // Lightweight in-memory store for browser dev mode
  const store = {
    signals: [],
    rules: [],
    features: {},
  };

  // Hydrate from localStorage
  try {
    const raw = localStorage.getItem(LS_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      store.signals = parsed.signals || [];
      store.rules = parsed.rules || [];
      store.features = parsed.features || {};
    }
  } catch {}

  const save = () => {
    try {
      // Cap at 5000 signals to fit localStorage
      if (store.signals.length > 5000) {
        store.signals = store.signals.slice(-5000);
      }
      localStorage.setItem(LS_KEY, JSON.stringify(store));
    } catch {}
  };

  _db = {
    _store: store,
    _save: save,
    isNode: false,
  };

  console.log(`[MLDb] Browser fallback initialized (${store.signals.length} signals cached)`);
  return _wrapApi(_db);
}

// ════════════════════════════════════════════════════════════════════
// UNIFIED API — same interface regardless of backend
// ════════════════════════════════════════════════════════════════════

function _wrapApi(db) {
  const api = {
    get raw() { return db; },
    get isNode() { return _isNode; },

    // ── INSERT SIGNALS (bulk, transactional) ──────────────────────

    /**
     * Bulk-insert trade signals in a single transaction.
     * @param {Array<object>} signals - each: {symbol, ts, direction, score100, rawScore, entryPrice, ...}
     * @returns {number} inserted count
     */
    insertSignals(signals) {
      if (!signals?.length) return 0;
      if (_isNode) return _insertSignalsNode(db, signals);
      return _insertSignalsBrowser(db, signals);
    },

    /**
     * Update outcome columns for signals by ID.
     * @param {Array<{id, t1Roi, t3Roi, t5Roi, outcome}>} outcomes
     */
    updateOutcomes(outcomes) {
      if (!outcomes?.length) return 0;
      if (_isNode) return _updateOutcomesNode(db, outcomes);
      return _updateOutcomesBrowser(db, outcomes);
    },

    // ── QUERY ─────────────────────────────────────────────────────

    /**
     * Get signals that still have null outcomes (need ROI backfill).
     * @param {number} [limit=1000]
     * @returns {Array<object>}
     */
    getOpenSignals(limit = 1000) {
      if (_isNode) {
        return db.prepare(`
          SELECT id, symbol, ts, direction, entry_price, stop_price, target_price, score100,
                 fired_signals, regime, setup_grade, sector
          FROM trade_signals
          WHERE outcome IS NULL OR outcome = 'OPEN'
          ORDER BY ts DESC LIMIT ?
        `).all(limit);
      }
      return db._store.signals
        .filter(s => !s.outcome || s.outcome === 'OPEN')
        .slice(-limit);
    },

    /**
     * Get closed signals with outcomes for rule discovery.
     * @param {object} [filters] - {direction, minScore, regime, sector, limit}
     * @returns {Array<object>}
     */
    getClosedSignals(filters = {}) {
      const { direction, minScore, regime, sector, limit = 5000 } = filters;
      if (_isNode) {
        let sql = `SELECT * FROM trade_signals WHERE outcome IS NOT NULL AND outcome != 'OPEN'`;
        const params = [];
        if (direction) { sql += ' AND direction = ?'; params.push(direction); }
        if (minScore != null) { sql += ' AND score100 >= ?'; params.push(minScore); }
        if (regime) { sql += ' AND regime = ?'; params.push(regime); }
        if (sector) { sql += ' AND sector = ?'; params.push(sector); }
        sql += ' ORDER BY ts DESC LIMIT ?';
        params.push(limit);
        return db.prepare(sql).all(...params);
      }
      let result = db._store.signals.filter(s => s.outcome && s.outcome !== 'OPEN');
      if (direction) result = result.filter(s => s.direction === direction);
      if (minScore != null) result = result.filter(s => (s.score100 || 0) >= minScore);
      return result.slice(-limit);
    },

    /**
     * Aggregate win rate by a specific feature bucket.
     * @param {string} feature - column name (rsi, mfi, cmf, etc.)
     * @param {number} bucketSize - bucket width
     * @param {string} [direction='BUY']
     */
    getFeatureBuckets(feature, bucketSize = 10, direction = 'BUY') {
      if (!_isNode) return [];
      // SQL floor-bucket aggregation
      return db.prepare(`
        SELECT
          CAST(FLOOR(${feature} / ?) * ? AS REAL) AS bucket_start,
          COUNT(*)                                 AS total,
          SUM(CASE WHEN actual_t1_roi > 0 THEN 1 ELSE 0 END) AS wins,
          AVG(actual_t1_roi)                       AS avg_roi,
          AVG(actual_t3_roi)                       AS avg_roi3
        FROM trade_signals
        WHERE direction = ? AND ${feature} IS NOT NULL AND outcome IS NOT NULL
        GROUP BY bucket_start
        HAVING total >= 5
        ORDER BY bucket_start
      `).all(bucketSize, bucketSize, direction);
    },

    /**
     * Get signal count and date range stats.
     */
    getStats() {
      if (_isNode) {
        const row = db.prepare(`
          SELECT
            COUNT(*)                                        AS total,
            SUM(CASE WHEN outcome IS NOT NULL THEN 1 END)  AS closed,
            SUM(CASE WHEN actual_t1_roi > 0 THEN 1 END)   AS wins,
            MIN(ts)                                        AS first_ts,
            MAX(ts)                                        AS last_ts,
            AVG(actual_t1_roi)                             AS avg_t1,
            AVG(actual_t3_roi)                             AS avg_t3
          FROM trade_signals
        `).get();
        return row || {};
      }
      const s = db._store.signals;
      const closed = s.filter(x => x.outcome && x.outcome !== 'OPEN');
      return {
        total: s.length,
        closed: closed.length,
        wins: closed.filter(x => (x.actual_t1_roi || 0) > 0).length,
        first_ts: s[0]?.ts,
        last_ts: s[s.length - 1]?.ts,
      };
    },

    // ── RULE PERSISTENCE ──────────────────────────────────────────

    /**
     * Upsert discovered rules (bulk).
     * @param {Array<object>} rules
     */
    upsertRules(rules) {
      if (!rules?.length) return;
      if (_isNode) return _upsertRulesNode(db, rules);
      db._store.rules = rules.slice(0, 500);
      db._save();
    },

    /**
     * Get top N active rules by win rate.
     * @param {number} [limit=20]
     * @param {number} [minOccurrences=10]
     */
    getTopRules(limit = 20, minOccurrences = 10) {
      if (_isNode) {
        return db.prepare(`
          SELECT * FROM discovered_rules
          WHERE is_active = 1 AND total_count >= ?
          ORDER BY expectancy DESC, win_rate_pct DESC
          LIMIT ?
        `).all(minOccurrences, limit);
      }
      return db._store.rules
        .filter(r => r.total_count >= minOccurrences)
        .sort((a, b) => (b.expectancy || 0) - (a.expectancy || 0))
        .slice(0, limit);
    },

    /**
     * Update feature importance scores.
     * @param {Array<{name, infoGain, correlation, sampleCount}>} features
     */
    updateFeatureImportance(features) {
      if (!features?.length) return;
      if (_isNode) {
        const stmt = db.prepare(`
          INSERT OR REPLACE INTO feature_importance (feature_name, info_gain, correlation, sample_count, last_updated)
          VALUES (?, ?, ?, ?, ?)
        `);
        const now = Date.now();
        const tx = db.transaction(() => {
          for (const f of features) {
            stmt.run(f.name, f.infoGain || 0, f.correlation || 0, f.sampleCount || 0, now);
          }
        });
        tx();
        return;
      }
      for (const f of features) db._store.features[f.name] = f;
      db._save();
    },

    getFeatureImportance() {
      if (_isNode) {
        return db.prepare('SELECT * FROM feature_importance ORDER BY info_gain DESC').all();
      }
      return Object.values(db._store.features || {}).sort((a, b) => (b.infoGain || 0) - (a.infoGain || 0));
    },

    // ── PAPER TRADING ──────────────────────────────────────────────

    /** Get portfolio state (singleton row). */
    getPaperPortfolio() {
      if (_isNode) {
        const row = db.prepare('SELECT * FROM paper_portfolio WHERE id = 1').get();
        if (!row) {
          // Auto-init
          db.prepare(`INSERT OR IGNORE INTO paper_portfolio (id, cash, start_capital, start_date, last_updated)
                       VALUES (1, 100000, 100000, ?, ?)`).run(Date.now(), Date.now());
          return db.prepare('SELECT * FROM paper_portfolio WHERE id = 1').get();
        }
        return row;
      }
      return null;
    },

    /** Update portfolio state. */
    updatePaperPortfolio(patch) {
      if (!_isNode) return;
      const fields = [];
      const params = {};
      for (const [k, v] of Object.entries(patch)) {
        const col = k.replace(/([A-Z])/g, '_$1').toLowerCase(); // camelCase → snake_case
        fields.push(`${col} = @${k}`);
        params[k] = v;
      }
      if (!fields.length) return;
      params.lastUpdated = Date.now();
      fields.push('last_updated = @lastUpdated');
      db.prepare(`UPDATE paper_portfolio SET ${fields.join(', ')} WHERE id = 1`).run(params);
    },

    /** Open a new paper trade. */
    openPaperTrade(trade) {
      if (!_isNode) return null;
      const stmt = db.prepare(`
        INSERT INTO paper_trades (
          symbol, direction, status, entry_price, stop_price, target_price,
          size_tl, lots, ml_confidence, ml_best_rule, ml_matched,
          confidence, grade, tier, score100, rr, sector, fired_signals,
          opened_at, entry_atr_pct, entry_rsi, entry_regime, notes
        ) VALUES (
          @symbol, @direction, 'OPEN', @entryPrice, @stopPrice, @targetPrice,
          @sizeTl, @lots, @mlConfidence, @mlBestRule, @mlMatched,
          @confidence, @grade, @tier, @score100, @rr, @sector, @firedSignals,
          @openedAt, @entryAtrPct, @entryRsi, @entryRegime, @notes
        )
      `);
      const info = stmt.run({
        symbol:       trade.symbol,
        direction:    trade.direction || 'BUY',
        entryPrice:   trade.entryPrice,
        stopPrice:    trade.stopPrice,
        targetPrice:  trade.targetPrice || null,
        sizeTl:       trade.sizeTl,
        lots:         trade.lots || 0,
        mlConfidence: trade.mlConfidence || null,
        mlBestRule:   trade.mlBestRule ? (typeof trade.mlBestRule === 'string' ? trade.mlBestRule : JSON.stringify(trade.mlBestRule)) : null,
        mlMatched:    trade.mlMatched || 0,
        confidence:   trade.confidence || null,
        grade:        trade.grade || null,
        tier:         trade.tier || null,
        score100:     trade.score100 || null,
        rr:           trade.rr || null,
        sector:       trade.sector || null,
        firedSignals: trade.firedSignals ? JSON.stringify(trade.firedSignals) : null,
        openedAt:     trade.openedAt || Date.now(),
        entryAtrPct:  trade.entryAtrPct || null,
        entryRsi:     trade.entryRsi || null,
        entryRegime:  trade.entryRegime ? (typeof trade.entryRegime === 'string' ? trade.entryRegime : JSON.stringify(trade.entryRegime)) : null,
        notes:        trade.notes || null,
      });
      return info.lastInsertRowid;
    },

    /** Close an open paper trade. */
    closePaperTrade(tradeId, exitPrice, exitReason) {
      if (!_isNode) return null;
      const trade = db.prepare('SELECT * FROM paper_trades WHERE id = ? AND status = ?').get(tradeId, 'OPEN');
      if (!trade) return null;

      const pnlTl  = (exitPrice - trade.entry_price) / trade.entry_price * trade.size_tl;
      const pnlPct = (exitPrice - trade.entry_price) / trade.entry_price * 100;
      const heldMs = Date.now() - trade.opened_at;

      db.prepare(`
        UPDATE paper_trades SET
          status = 'CLOSED', exit_price = ?, exit_reason = ?,
          pnl_tl = ?, pnl_pct = ?, closed_at = ?, held_ms = ?
        WHERE id = ?
      `).run(exitPrice, exitReason, Math.round(pnlTl * 100) / 100,
             Math.round(pnlPct * 100) / 100, Date.now(), heldMs, tradeId);

      return { pnlTl: Math.round(pnlTl * 100) / 100, pnlPct: Math.round(pnlPct * 100) / 100, heldMs };
    },

    /** Get open paper trades. */
    getOpenPaperTrades() {
      if (!_isNode) return [];
      return db.prepare('SELECT * FROM paper_trades WHERE status = ? ORDER BY opened_at DESC').all('OPEN');
    },

    /** Get closed paper trades. */
    getClosedPaperTrades(limit = 200) {
      if (!_isNode) return [];
      return db.prepare('SELECT * FROM paper_trades WHERE status = ? ORDER BY closed_at DESC LIMIT ?').all('CLOSED', limit);
    },

    /** Get paper trading performance stats. */
    getPaperStats() {
      if (!_isNode) return {};
      const portfolio = db.prepare('SELECT * FROM paper_portfolio WHERE id = 1').get();
      const stats = db.prepare(`
        SELECT
          COUNT(*)                                       AS total_trades,
          SUM(CASE WHEN pnl_tl > 0 THEN 1 ELSE 0 END) AS wins,
          SUM(CASE WHEN pnl_tl <= 0 THEN 1 ELSE 0 END) AS losses,
          SUM(pnl_tl)                                    AS total_pnl,
          AVG(CASE WHEN pnl_tl > 0 THEN pnl_pct END)   AS avg_win_pct,
          AVG(CASE WHEN pnl_tl <= 0 THEN pnl_pct END)  AS avg_loss_pct,
          AVG(pnl_pct)                                   AS avg_pnl_pct,
          MAX(pnl_pct)                                   AS best_trade_pct,
          MIN(pnl_pct)                                   AS worst_trade_pct,
          AVG(held_ms)                                   AS avg_held_ms
        FROM paper_trades WHERE status = 'CLOSED'
      `).get();

      // ML-specific: win rate by ML confidence bucket
      const mlBuckets = db.prepare(`
        SELECT
          CASE
            WHEN ml_confidence >= 5 THEN 'HIGH'
            WHEN ml_confidence >= 2 THEN 'MEDIUM'
            WHEN ml_confidence >= 1 THEN 'LOW'
            ELSE 'NONE'
          END AS ml_tier,
          COUNT(*)                                       AS cnt,
          SUM(CASE WHEN pnl_tl > 0 THEN 1 ELSE 0 END) AS wins,
          AVG(pnl_pct)                                   AS avg_pnl
        FROM paper_trades WHERE status = 'CLOSED'
        GROUP BY ml_tier
      `).all();

      return { portfolio, ...stats, mlBuckets };
    },

    /** Reset paper trading (fresh start). */
    resetPaperTrading() {
      if (!_isNode) return;
      const tx = db.transaction(() => {
        db.prepare('DELETE FROM paper_trades').run();
        db.prepare(`UPDATE paper_portfolio SET
          cash = 100000, start_capital = 100000, start_date = ?,
          total_trades = 0, wins = 0, losses = 0, total_pnl = 0,
          max_drawdown = 0, peak_equity = 100000, last_updated = ?
        WHERE id = 1`).run(Date.now(), Date.now());
      });
      tx();
    },

    // ── MAINTENANCE ───────────────────────────────────────────────

    /** Vacuum old signals (keep last N months). */
    prune(monthsToKeep = 6) {
      const cutoff = Date.now() - monthsToKeep * 30 * 86400000;
      if (_isNode) {
        const info = db.prepare('DELETE FROM trade_signals WHERE ts < ? AND outcome IS NOT NULL').run(cutoff);
        db.pragma('wal_checkpoint(TRUNCATE)');
        return info.changes;
      }
      const before = db._store.signals.length;
      db._store.signals = db._store.signals.filter(s => s.ts >= cutoff || !s.outcome);
      db._save();
      return before - db._store.signals.length;
    },

    close() {
      if (_isNode && db.open) {
        db.pragma('wal_checkpoint(TRUNCATE)');
        db.close();
      }
      _db = null;
    },
  };

  return api;
}

// ════════════════════════════════════════════════════════════════════
// NODE.JS BULK OPERATIONS (better-sqlite3 prepared stmts + transactions)
// ════════════════════════════════════════════════════════════════════

function _insertSignalsNode(db, signals) {
  const stmt = db.prepare(`
    INSERT INTO trade_signals (
      symbol, ts, direction, score100, raw_score, entry_price, stop_price, target_price, rr,
      atr, atr_pct, rsi, mfi, adx, cmf, vol_ratio, boll_pct,
      dist_ma20_pct, dist_ma50_pct, dist_ma200_pct,
      obv_trend, wyckoff_phase, supertrend_dir, ichimoku_pos,
      ttm_squeeze, ttm_fire, fired_signals,
      regime, setup_grade, sector, technical_state
    ) VALUES (
      @symbol, @ts, @direction, @score100, @rawScore, @entryPrice, @stopPrice, @targetPrice, @rr,
      @atr, @atrPct, @rsi, @mfi, @adx, @cmf, @volRatio, @bollPct,
      @distMa20, @distMa50, @distMa200,
      @obvTrend, @wyckoffPhase, @supertrendDir, @ichimokuPos,
      @ttmSqueeze, @ttmFire, @firedSignals,
      @regime, @setupGrade, @sector, @technicalState
    )
  `);

  const tx = db.transaction((batch) => {
    let count = 0;
    for (const s of batch) {
      stmt.run(_mapSignalToRow(s));
      count++;
    }
    return count;
  });

  return tx(signals);
}

function _mapSignalToRow(s) {
  // Accept both flat advisor-scan results and genSignal output
  const ind = s.indicators || s.ind || {};
  return {
    symbol:        s.symbol,
    ts:            s.ts || s._scanTs || Date.now(),
    direction:     s.direction || s.cls?.toUpperCase() || (s.score100 >= 60 ? 'BUY' : s.score100 <= 40 ? 'SELL' : 'HOLD'),
    score100:      s.score100 ?? s.score ?? null,
    rawScore:      s.rawScore ?? s.raw_score ?? null,
    entryPrice:    s.entry_price ?? s.entry ?? s.price ?? 0,
    stopPrice:     s.stop_price ?? s.stop ?? null,
    targetPrice:   s.target_price ?? s.target ?? s.t1 ?? null,
    rr:            s.rr ?? null,
    atr:           s.atr ?? ind.atr ?? null,
    atrPct:        s.atr_pct ?? s.atrPct ?? null,
    rsi:           s.rsi ?? ind.lastRSI ?? null,
    mfi:           s.mfi ?? ind.mfi ?? null,
    adx:           s.adx ?? ind.adx ?? null,
    cmf:           s.cmf ?? ind.cmf ?? null,
    volRatio:      s.vol_ratio ?? s.volRatio ?? ind.volRatio ?? null,
    bollPct:       s.boll_pct ?? s.bollPct ?? null,
    distMa20:      s.dist_ma20_pct ?? s.distFromMA20 ?? null,
    distMa50:      s.dist_ma50_pct ?? s.ma50pct ?? null,
    distMa200:     s.dist_ma200_pct ?? null,
    obvTrend:      s.obv_trend ?? s.obvTrend ?? ind.obvTrend ?? null,
    wyckoffPhase:  s.wyckoff_phase ?? s.wyckoff ?? ind.wyckoffPhase ?? null,
    supertrendDir: s.supertrend_dir ?? s.supertrend?.trend ?? ind.supertrend?.trend ?? null,
    ichimokuPos:   s.ichimoku_pos ?? s.ichimoku?.cloudPosition ?? null,
    ttmSqueeze:    (s.ttmSqueeze?.squeezeOn || s.ttm_squeeze) ? 1 : 0,
    ttmFire:       (s.ttmSqueeze?.firing || s.ttm_fire) ? 1 : 0,
    firedSignals:  s.fired_signals ?? (s.firedSignals ? JSON.stringify(s.firedSignals) : null),
    regime:        s.regime?.regime ?? s.regime ?? null,
    setupGrade:    s.setup_grade ?? s.setupGrade ?? null,
    sector:        s.sector ?? null,
    technicalState: s.technical_state ?? (s._fullTechnicalState ? JSON.stringify(s._fullTechnicalState) : null),
  };
}

function _updateOutcomesNode(db, outcomes) {
  const stmt = db.prepare(`
    UPDATE trade_signals
    SET actual_t1_roi = COALESCE(@t1Roi, actual_t1_roi),
        actual_t3_roi = COALESCE(@t3Roi, actual_t3_roi),
        actual_t5_roi = COALESCE(@t5Roi, actual_t5_roi),
        outcome       = @outcome,
        outcome_ts    = @outcomeTs
    WHERE id = @id
  `);

  const tx = db.transaction((batch) => {
    let count = 0;
    for (const o of batch) {
      const info = stmt.run({
        id:        o.id,
        t1Roi:     o.t1Roi ?? o.actual_t1_roi ?? null,
        t3Roi:     o.t3Roi ?? o.actual_t3_roi ?? null,
        t5Roi:     o.t5Roi ?? o.actual_t5_roi ?? null,
        outcome:   o.outcome || (o.t1Roi > 0 ? 'WIN' : o.t1Roi != null ? 'LOSS' : 'OPEN'),
        outcomeTs: o.outcomeTs || Date.now(),
      });
      count += info.changes;
    }
    return count;
  });

  return tx(outcomes);
}

// ── WEIGHTED MERGE UPSERT — Continuous Learning Rule Memory ──────
//
// Instead of overwriting old rules, we merge new training data with existing
// historical observations using a weighted average. This preserves old regime
// knowledge (market regimes are cyclical — 2021 bull rules reappear in 2024).
//
// Formula:
//   mergedWinRate = (old.winCount + new.winCount) / (old.totalCount + new.totalCount)
//   mergedAvgRoi  = (old.avgRoi * old.totalCount + new.avgRoi * new.totalCount) / totalMerged
//   expectancy    = mergedAvgWin * mergedWinRate + mergedAvgLoss * (1 - mergedWinRate)
//
// Rules not seen in 6+ months get a decay factor (0.85) applied to their
// sample count, naturally letting stale rules lose weight over time without
// forgetting them entirely.

function _upsertRulesNode(db, rules) {
  const now = Date.now();

  // Fetch existing rule by hash (for merge calculation)
  const selectStmt = db.prepare('SELECT * FROM discovered_rules WHERE rule_hash = ?');

  // Fresh insert (no existing rule)
  const insertStmt = db.prepare(`
    INSERT INTO discovered_rules (
      rule_hash, setup_name, conditions, direction,
      total_count, win_count, loss_count, win_rate_pct,
      avg_roi_pct, avg_win_roi, avg_loss_roi,
      expectancy, sharpe, max_drawdown, profit_factor,
      last_updated, created_at, last_seen_date, regime_tags, is_active
    ) VALUES (
      @ruleHash, @setupName, @conditions, @direction,
      @totalCount, @winCount, @lossCount, @winRatePct,
      @avgRoiPct, @avgWinRoi, @avgLossRoi,
      @expectancy, @sharpe, @maxDrawdown, @profitFactor,
      @lastUpdated, @createdAt, @lastSeenDate, @regimeTags, 1
    )
  `);

  // Weighted merge update (existing rule)
  const updateStmt = db.prepare(`
    UPDATE discovered_rules SET
      total_count   = @totalCount,
      win_count     = @winCount,
      loss_count    = @lossCount,
      win_rate_pct  = @winRatePct,
      avg_roi_pct   = @avgRoiPct,
      avg_win_roi   = @avgWinRoi,
      avg_loss_roi  = @avgLossRoi,
      expectancy    = @expectancy,
      sharpe        = @sharpe,
      max_drawdown  = @maxDrawdown,
      profit_factor = @profitFactor,
      last_updated  = @lastUpdated,
      last_seen_date = @lastSeenDate,
      regime_tags   = @regimeTags,
      is_active     = 1
    WHERE rule_hash = @ruleHash
  `);

  const tx = db.transaction((batch) => {
    let merged = 0, inserted = 0;

    for (const r of batch) {
      const hash = r.rule_hash || r.ruleHash;
      const newTotal = r.total_count ?? r.totalCount ?? 0;
      const newWins  = r.win_count ?? r.winCount ?? 0;
      const newLosses = r.loss_count ?? r.lossCount ?? 0;
      const newAvgRoi = r.avg_roi_pct ?? r.avgRoiPct ?? 0;
      const newAvgWin = r.avg_win_roi ?? r.avgWinRoi ?? 0;
      const newAvgLoss = r.avg_loss_roi ?? r.avgLossRoi ?? 0;
      const newSharpe = r.sharpe ?? 0;
      const newDD = r.max_drawdown ?? r.maxDrawdown ?? 0;
      const newPF = r.profit_factor ?? r.profitFactor ?? 0;

      const existing = selectStmt.get(hash);

      if (existing) {
        // ── Weighted Merge ──
        // Apply decay to old observations if rule wasn't seen recently (6+ months)
        const SIX_MONTHS_MS = 180 * 24 * 60 * 60 * 1000;
        const lastSeen = existing.last_seen_date || existing.last_updated || now;
        const isStale = (now - lastSeen) > SIX_MONTHS_MS;
        const decayFactor = isStale ? 0.85 : 1.0;

        const oldTotal  = Math.round((existing.total_count || 0) * decayFactor);
        const oldWins   = Math.round((existing.win_count || 0) * decayFactor);
        const oldLosses = Math.round((existing.loss_count || 0) * decayFactor);

        const mTotal  = oldTotal + newTotal;
        const mWins   = oldWins + newWins;
        const mLosses = oldLosses + newLosses;

        if (mTotal === 0) continue; // degenerate — skip

        const mWinRate = (mWins / mTotal) * 100;
        const mAvgRoi  = mTotal > 0
          ? ((existing.avg_roi_pct || 0) * oldTotal + newAvgRoi * newTotal) / mTotal
          : 0;

        // Weighted merge of avg_win_roi and avg_loss_roi
        const mAvgWin = mWins > 0
          ? ((existing.avg_win_roi || 0) * oldWins + newAvgWin * newWins) / mWins
          : 0;
        const mAvgLoss = mLosses > 0
          ? ((existing.avg_loss_roi || 0) * oldLosses + newAvgLoss * newLosses) / mLosses
          : 0;

        // Recompute expectancy from merged values
        const winRate01 = mWinRate / 100;
        const mExpectancy = (mAvgWin * winRate01) + (mAvgLoss * (1 - winRate01));

        // Weighted merge for sharpe, maxDD, profitFactor
        const mSharpe = mTotal > 0
          ? ((existing.sharpe || 0) * oldTotal + newSharpe * newTotal) / mTotal
          : 0;
        const mDD = Math.min(existing.max_drawdown || 0, newDD); // worst of both
        const mPF = mTotal > 0
          ? ((existing.profit_factor || 0) * oldTotal + newPF * newTotal) / mTotal
          : 0;

        // Merge regime tags (union of old + new)
        let regimeTags = [];
        try { regimeTags = JSON.parse(existing.regime_tags || '[]'); } catch {}
        if (r.regime && !regimeTags.includes(r.regime)) regimeTags.push(r.regime);

        updateStmt.run({
          ruleHash:     hash,
          totalCount:   mTotal,
          winCount:     mWins,
          lossCount:    mLosses,
          winRatePct:   Math.round(mWinRate * 100) / 100,
          avgRoiPct:    Math.round(mAvgRoi * 100) / 100,
          avgWinRoi:    Math.round(mAvgWin * 100) / 100,
          avgLossRoi:   Math.round(mAvgLoss * 100) / 100,
          expectancy:   Math.round(mExpectancy * 100) / 100,
          sharpe:       Math.round(mSharpe * 1000) / 1000,
          maxDrawdown:  Math.round(mDD * 100) / 100,
          profitFactor: Math.round(mPF * 100) / 100,
          lastUpdated:  now,
          lastSeenDate: now,
          regimeTags:   JSON.stringify(regimeTags),
        });
        merged++;
      } else {
        // ── Fresh Insert ──
        const winRate = newTotal > 0 ? (newWins / newTotal) * 100 : 0;
        insertStmt.run({
          ruleHash:     hash,
          setupName:    r.setup_name || r.setupName,
          conditions:   typeof r.conditions === 'string' ? r.conditions : JSON.stringify(r.conditions),
          direction:    r.direction || 'BUY',
          totalCount:   newTotal,
          winCount:     newWins,
          lossCount:    newLosses,
          winRatePct:   r.win_rate_pct ?? r.winRatePct ?? winRate,
          avgRoiPct:    newAvgRoi,
          avgWinRoi:    newAvgWin,
          avgLossRoi:   newAvgLoss,
          expectancy:   r.expectancy ?? 0,
          sharpe:       newSharpe,
          maxDrawdown:  newDD,
          profitFactor: newPF,
          lastUpdated:  now,
          createdAt:    now,
          lastSeenDate: now,
          regimeTags:   r.regime ? JSON.stringify([r.regime]) : '[]',
        });
        inserted++;
      }
    }

    console.log(`[MLDb] Rule upsert: ${inserted} new, ${merged} merged (weighted)`);
    return { inserted, merged };
  });

  return tx(rules);
}

// ── BROWSER FALLBACK BULK OPS ──────────────────────────────────────

function _insertSignalsBrowser(db, signals) {
  for (const s of signals) {
    db._store.signals.push({
      id: db._store.signals.length + 1,
      ..._mapSignalToRow(s),
      actual_t1_roi: null, actual_t3_roi: null, actual_t5_roi: null,
      outcome: null, outcome_ts: null,
    });
  }
  db._save();
  return signals.length;
}

function _updateOutcomesBrowser(db, outcomes) {
  const idMap = new Map(db._store.signals.map((s, i) => [s.id, i]));
  let count = 0;
  for (const o of outcomes) {
    const idx = idMap.get(o.id);
    if (idx == null) continue;
    const s = db._store.signals[idx];
    if (o.t1Roi != null) s.actual_t1_roi = o.t1Roi;
    if (o.t3Roi != null) s.actual_t3_roi = o.t3Roi;
    if (o.t5Roi != null) s.actual_t5_roi = o.t5Roi;
    s.outcome = o.outcome || (o.t1Roi > 0 ? 'WIN' : o.t1Roi != null ? 'LOSS' : 'OPEN');
    s.outcome_ts = Date.now();
    count++;
  }
  db._save();
  return count;
}

// ════════════════════════════════════════════════════════════════════
// IPC BRIDGE — Electron main process handler registration
// ════════════════════════════════════════════════════════════════════

/**
 * Call from electron/main.cjs to register IPC handlers.
 * Usage:  import('../src/utils/DatabaseManager.js').then(({ registerMLDbIPC }) => registerMLDbIPC(ipcMain));
 *         registerMLDbIPC(ipcMain);
 */
export async function registerMLDbIPC(ipcMain) {
  const db = await initMLDatabase();

  ipcMain.handle('mldb:insertSignals',   (_e, signals)  => db.insertSignals(signals));
  ipcMain.handle('mldb:updateOutcomes',  (_e, outcomes)  => db.updateOutcomes(outcomes));
  ipcMain.handle('mldb:getOpenSignals',  (_e, limit)     => db.getOpenSignals(limit));
  ipcMain.handle('mldb:getClosedSignals',(_e, filters)   => db.getClosedSignals(filters));
  ipcMain.handle('mldb:getStats',        ()              => db.getStats());
  ipcMain.handle('mldb:getTopRules',     (_e, limit, min)=> db.getTopRules(limit, min));
  ipcMain.handle('mldb:upsertRules',     (_e, rules)     => db.upsertRules(rules));
  ipcMain.handle('mldb:getFeatureBuckets', (_e, feat, bs, dir) => db.getFeatureBuckets(feat, bs, dir));
  ipcMain.handle('mldb:getFeatureImportance', ()         => db.getFeatureImportance());
  ipcMain.handle('mldb:updateFeatureImportance', (_e, f) => db.updateFeatureImportance(f));
  ipcMain.handle('mldb:prune',           (_e, months)    => db.prune(months));

  // Paper Trading IPC
  ipcMain.handle('paper:getPortfolio',      ()              => db.getPaperPortfolio());
  ipcMain.handle('paper:updatePortfolio',   (_e, patch)     => db.updatePaperPortfolio(patch));
  ipcMain.handle('paper:openTrade',         (_e, trade)     => db.openPaperTrade(trade));
  ipcMain.handle('paper:closeTrade',        (_e, id, price, reason) => db.closePaperTrade(id, price, reason));
  ipcMain.handle('paper:getOpenTrades',     ()              => db.getOpenPaperTrades());
  ipcMain.handle('paper:getClosedTrades',   (_e, limit)     => db.getClosedPaperTrades(limit));
  ipcMain.handle('paper:getStats',          ()              => db.getPaperStats());
  ipcMain.handle('paper:reset',             ()              => db.resetPaperTrading());

  console.log('[MLDb] IPC handlers registered (including paper trading)');
  return db;
}

export default { initMLDatabase, registerMLDbIPC };
