// Builds engine-rs (Rust) to WebAssembly and embeds it as base64 in
// src/engine/bistEngineWasm.js — so the Vercel / PWA / Electron / Capacitor
// builds need no Rust toolchain and no .wasm fetch (Electron loads from file://).
//
//   npm run build:engine          (needs rustup + the wasm32-unknown-unknown target)
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { engineSourceHash } from './engine-hash.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const crate = join(root, 'engine-rs');
const exe = process.platform === 'win32' ? 'cargo.exe' : 'cargo';
const cargo = process.env.CARGO || (existsSync(join(homedir(), '.cargo', 'bin', exe)) ? join(homedir(), '.cargo', 'bin', exe) : exe);

execFileSync(cargo, ['build', '--release', '--target', 'wasm32-unknown-unknown'], { cwd: crate, stdio: 'inherit' });

const wasm = readFileSync(join(crate, 'target', 'wasm32-unknown-unknown', 'release', 'bist_engine.wasm'));
const hash = engineSourceHash(crate);
const out = join(root, 'src', 'engine', 'bistEngineWasm.js');
writeFileSync(out,
  '// GENERATED by scripts/build-engine.mjs — do not edit. Rebuild: npm run build:engine\n'
  + `export const ENGINE_SOURCE_HASH = '${hash}';\n`
  + `export const ENGINE_WASM_BYTES = ${wasm.length};\n`
  + `export const ENGINE_WASM_BASE64 = '${wasm.toString('base64')}';\n`);
console.log(`engine: ${wasm.length} bytes wasm → ${out} (source hash ${hash})`);
